import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@shared/styles/globals.css';
import { Toaster } from '@shared/ui/Sonner';
import { AuthHydrator } from '@/shared/auth/AuthHydrator';
import { getUserWithProfile } from '@/shared/auth/getUserWithProfile';
import type { SessionUser } from '@/shared/auth/types';
import type { Profile } from '@/shared/auth/types/profile.types';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Modify getInitialUser to use getUserWithProfile
async function getInitialUser(): Promise<{
  supabaseUser: SessionUser | null;
  profile: Profile | null;
}> {
  const { supabaseUser, profile } = await getUserWithProfile();
  return { supabaseUser, profile };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialUser = await getInitialUser();
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthHydrator initialUser={initialUser} />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
