import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@shared/styles/globals.css';
import { UserProvider } from '@/shared/provider/UserProvider';
import { getUserWithProfile } from '@/shared/auth/getUserWithProfile';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserWithProfile();
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider initialUser={user}>{children}</UserProvider>
      </body>
    </html>
  );
}
